name: Update README
on:
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: Fishskin713/github-activity-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          GH_USERNAME: "Fishskin713"
          COMMIT_MSG: "Specify a custom commit message"
          MAX_LINES: 10
          COMMIT_NAME: GitHub Activity Readme
