name: Update GitHub Activity
on:
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_TOKEN }}
      
      - name: GitHub README Activity Updater
        uses: ggofri/github-activity-updater@v1.1.0
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
          username: "Fishskin713"
