name: Update README
on:
  workflow_dispatch:
jobs:
  build:
    name: GitHub - Activity - Readme
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@v0.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          GH_USERNAME: "Fishskin713"
